# Generated by Django 3.0.5 on 2023-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_mytitlesuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytitlesuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Administrator'), ('django_admin', 'Django Administrator')], default='user', max_length=15),
        ),
        migrations.AddField(
            model_name='mytitlesuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
