# Generated by Django 4.1.7 on 2023-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230329_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytitlesuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
